version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: bootcamp
      POSTGRES_PASSWORD: bootcamp
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  clamav:
    image: openbridge/clamav
    container_name: clamav
    ports:
      - 3310:3310
    tty: true
    restart: unless-stopped
    tmpfs: /var/cache
    volumes:
      - clamd_data:/var/lib/clamav
    ulimits:
      nproc: 65535
      nofile:
        soft: 49999
        hard: 99999

networks:
  default:
    driver: bridge

volumes:
  clamd_data:
    driver: local
